{{- include "rspamd.validateRedis" . -}}
{{- if and .Values.config.workerController.enabled .Values.config.workerController.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rspamd.controllerConfigSecretName" . }}
  labels:
    {{- include "rspamd.labels" . | nindent 4 }}
type: Opaque
stringData:
  worker-controller.inc: |
{{ include "rspamd.workerControllerConfig" . | nindent 4 }}
{{- end }}
