{{- include "rspamd.validateRedis" . -}}
{{- if .Values.externalRedis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rspamd.redisConfigSecretName" . }}
  labels:
    {{- include "rspamd.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis.conf: |
{{ include "rspamd.redisConfig" . | nindent 4 }}
{{- if .Values.config.historyRedis.enabled }}
  history_redis.conf: |
{{ include "rspamd.historyRedisConfig" . | nindent 4 }}
{{- end }}
{{- end }}
