apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "adminer.fullname" . }}
  labels:
    {{- include "adminer.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "adminer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "adminer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "adminer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if or .Values.env .Values.postgresqlTls.enabled }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .Values.postgresqlTls.enabled }}
            - name: "PGSSLMODE"
              value: {{ .Values.postgresqlTls.sslMode | quote }}
            - name: "PGSSLROOTCERT"
              value: "{{ clean .Values.postgresqlTls.mountPath }}/{{ .Values.postgresqlTls.caKey }}"
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- if or .Values.mysqlTls.enabled .Values.postgresqlTls.enabled }}
          volumeMounts:
            {{- if .Values.mysqlTls.enabled }}
            - name: mysql-tls
              mountPath: {{ .Values.mysqlTls.mountPath | quote }}
              readOnly: true
            - name: mysql-tls-plugin
              mountPath: /var/www/html/plugins-enabled/001-login-ssl.php
              subPath: 001-login-ssl.php
              readOnly: true
            {{- end }}
            {{- if .Values.postgresqlTls.enabled }}
            - name: postgresql-tls
              mountPath: {{ .Values.postgresqlTls.mountPath | quote }}
              readOnly: true
            - name: postgresql-tls-plugin
              mountPath: /var/www/html/plugins-enabled/001-postgresql-login-ssl.php
              subPath: 001-postgresql-login-ssl.php
              readOnly: true
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if or .Values.mysqlTls.enabled .Values.postgresqlTls.enabled }}
      volumes:
        {{- if .Values.mysqlTls.enabled }}
        - name: mysql-tls
          secret:
            secretName: {{ required "mysqlTls.secretName is required when mysqlTls.enabled=true" .Values.mysqlTls.secretName | quote }}
        - name: mysql-tls-plugin
          configMap:
            name: {{ include "adminer.fullname" . }}-mysql-tls-plugin
        {{- end }}
        {{- if .Values.postgresqlTls.enabled }}
        - name: postgresql-tls
          secret:
            secretName: {{ required "postgresqlTls.secretName is required when postgresqlTls.enabled=true" .Values.postgresqlTls.secretName | quote }}
        - name: postgresql-tls-plugin
          configMap:
            name: {{ include "adminer.fullname" . }}-postgresql-tls-plugin
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
