name: rspamd

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/rspamd.yml'
      - 'rspamd/**'
  pull_request:
    paths:
      - '.github/workflows/rspamd.yml'
      - 'rspamd/**'
  workflow_dispatch:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: raven-actions/actionlint@v2

  build:
    needs: actionlint
    uses: ectobit/reusable-workflows/.github/workflows/chart.yaml@main
    with:
      chart: rspamd
    secrets:
      helm-repo-username: ${{secrets.HELM_REPO_USERNAME}}
      helm-repo-password: ${{secrets.HELM_REPO_PASSWORD}}
      gpg-signing-key: ${{ secrets.GPG_SIGNING_KEY }}
